number of fixes
- '-t' opt to set tags on imgapi-standalone-create
- fix imgapi-standalone-gen-setup-config for new dir location
- drop the pipe-through grep for manta-sync in imgapi-stanalone-restore
  because don't want to rely on pipefail to catch a manta-sync non-zero
  exit (very important it fails on sync failures)
- notice a 403 Forbidden error to Manta in imgapi-stanalone-status
- manta-env usage in ~/.profile shouldn't squak if there isn't a
  imgapi.config.json file

diff --git a/bin/manta-env b/bin/manta-env
--- a/bin/manta-env
+++ b/bin/manta-env
@@ -28,13 +28,13 @@ JSON=json
 # ---- support stuff
 
 function fatal {
-    echo "$0: fatal error: $*"
+    echo "$0: fatal error: $*" >&2
     exit 1
 }
 
 function errexit {
     [[ $1 -ne 0 ]] || exit 0
-    fatal "error exit status $1"
+    fatal "error exit status $1" >&2
 }
 
 
