IMGAPI-24, IMGAPI-19: fix for ActivateImage; impl and tests for CreateImage

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -70,7 +70,8 @@ NODEUNIT=./node_modules/.bin/nodeunit
 opt_just_clean=
 opt_test_pattern=
 opt_quick=
-while getopts "hcqf:" opt
+opt_reporter=tap
+while getopts "hcqf:r:" opt
 do
     case "$opt" in
         h)
@@ -85,6 +86,9 @@ do
             ;;
         f)
             opt_test_pattern=$OPTARG
+            ;;
+        r)
+            opt_reporter=$OPTARG
             ;;
         *)
             usage
@@ -143,42 +147,51 @@ fi
 
 # Run the tests.
 echo ""
+retval=0
 test_files=$(ls -1 test/*.test.js)
 if [[ -n "$opt_test_pattern" ]]; then
     test_files=$(echo "$test_files" | grep "$opt_test_pattern" || true)
     echo "# Running filtered set of test files: $test_files"
 fi
 if [[ -n "$test_files" ]]; then
-    PATH=$NODE_INSTALL/bin:$PATH $NODEUNIT --reporter tap $test_files \
-        | tee $OUTPUT_DIR/imgapi.tap
+    if [[ $opt_reporter == "tap" ]]; then
+        PATH=$NODE_INSTALL/bin:$PATH $NODEUNIT --reporter $opt_reporter $test_files \
+            | tee $OUTPUT_DIR/imgapi.tap
+    else
+        PATH=$NODE_INSTALL/bin:$PATH $NODEUNIT --reporter $opt_reporter $test_files
+        retval=$?
+    fi
 fi
 
 
-echo ""
-echo "# test output:"
-ls $OUTPUT_DIR/*.tap
+if [[ $opt_reporter == "tap" ]]; then
+    echo ""
+    echo "# test output:"
+    ls $OUTPUT_DIR/*.tap
 
+    # Colored summary of results (borrowed from smartos-live.git/src/vm/run-tests).
+    echo ""
+    echo "# test results:"
 
-# Colored summary of results (borrowed from smartos-live.git/src/vm/run-tests).
-echo ""
-echo "# test results:"
+    end_time=$(date +%s)
+    elapsed=$((${end_time} - ${start_time}))
 
-end_time=$(date +%s)
-elapsed=$((${end_time} - ${start_time}))
+    tests=$(grep "^# tests [0-9]" $OUTPUT_DIR/*.tap | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
+    passed=$(grep "^# pass  [0-9]" $OUTPUT_DIR/*.tap | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
+    [[ -z ${tests} ]] && tests=0
+    [[ -z ${passed} ]] && passed=0
+    fail=$((${tests} - ${passed}))
 
-tests=$(grep "^# tests [0-9]" $OUTPUT_DIR/*.tap | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
-passed=$(grep "^# pass  [0-9]" $OUTPUT_DIR/*.tap | tr -s ' ' | cut -d ' ' -f3 | xargs | tr ' ' '+' | bc)
-[[ -z ${tests} ]] && tests=0
-[[ -z ${passed} ]] && passed=0
-fail=$((${tests} - ${passed}))
+    echo "# Completed in ${elapsed} seconds."
+    echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
+    if [[ ${fail} -gt 0 ]]; then
+        echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
+    fi
+    echo ""
 
-echo "# Completed in ${elapsed} seconds."
-echo -e "# \033[32mPASS: ${passed} / ${tests}\033[39m"
-if [[ ${fail} -gt 0 ]]; then
-    echo -e "# \033[31mFAIL: ${fail} / ${tests}\033[39m"
-fi
-echo ""
-
-if [[ ${tests} != ${passed} ]]; then
-    exit 1
+    if [[ ${tests} != ${passed} ]]; then
+        exit 1
+    fi
+else
+    exit $retval
 fi
