a bunch of work

diff --git a/tools/standalone/sbin/imgapi-standalone-create b/tools/standalone/sbin/imgapi-standalone-create
--- a/tools/standalone/sbin/imgapi-standalone-create
+++ b/tools/standalone/sbin/imgapi-standalone-create
@@ -29,7 +29,8 @@ function usage () {
     echo ""
     echo "Options:"
     echo "  -h          Show this help and exit."
-    echo "  -m KEY=VAL  Instance metadata (used to configure the IMGAPI)."
+    echo "  -m KEY=VAL  Setup config var to add to metadata (used by initial "
+    echo "              setup to configure IMGAPI)."
     #TODO: -c CHANNEL    option
     #XXX more doc
 }
@@ -137,18 +138,20 @@ netUuid=$(echo "$netJson" | json uuid)
 netName=$(echo "$netJson" | json name)
 
 # Create the VM
+vmUuid=$(uuid)
+optMetadata=$(echo "$optMetadata" \
+    | json -e "this['user-script'] = '/opt/smartdc/imgapi/tools/standalone/user-script'")
 echo ""
 echo "Creating standalone imgapi VM:"
+echo "       uuid: $vmUuid"
 echo "      alias: $ALIAS"
 echo "      owner: $ownerUuid ($ownerLogin)"
 echo "      image: $imageUuid ($imageName@$imageVersion)"
 echo "    package: $packageUuid ($packageName)"
 echo "    network: $netUuid ($netName)"
-echo "   metadata: $optMetadata"
+echo "   metadata:"
+echo "$optMetadata" | sed  's/^/        /'
 echo ""
-vmUuid=$(uuid)
-optMetadata=$(echo "$optMetadata" \
-    | json -e "this['user-script'] = '/opt/smartdc/imgapi/tools/standalone/user-script'")
 sdc-vmapi /vms -X POST -d@- <<EOP | json -H | sdc-waitforjob
 {
     "uuid": "$vmUuid",
@@ -165,26 +168,59 @@ EOP
 
 # ^^^ does that exit non-zero on job failure? It would be nice.
 
+# Poll until get a 200 status ping (give it up to 2 minutes)
+echo ""
+echo "Waiting for IMGAPI service ping to respond with a 200"
+MAX_TRIES=40
+instIp=$(sdc-vmadm get $vmUuid | json nics | json -c 'this.primary' 0.ip)
+[[ -n $instIp ]] || fatal "could not determine VM $vmUuid primary IP"
+nTries=0
+pingResponse=
+pingStatus=
+while [[ nTries -lt $MAX_TRIES ]]; do
+    sleep 3
+    echo -n '.'
+    pingResponse=$(curl -ski --connect-timeout 2 --max-time 5 https://$instIp/ping || true)
+    pingStatus=$(echo "$pingResponse" | head -1 | awk '{print $2}')
+    if [[ $pingStatus == "200" ]]; then
+        break
+    fi
+    nTries=$(( $nTries + 1 ))
+done
+if [[ $pingStatus != "200" ]]; then
+    fatal "timeout waiting for IMGAPI ping to respond with 200:
+--
+$pingResponse
+--"
+fi
+echo ""
+
 mantaUser=$(echo "$optMetadata" | json mantaUser)
 if [[ -n "$mantaUser" ]]; then
     # Configured for Manta: show the command needed to get the imgapi instance
     # key on the user.
     echo ""
+    echo "* * *"
     echo "For this IMGAPI instance to talk to Manta, its instance SSH key"
     echo "needs to be added to the '$mantaUser' account. If the Manta being"
     echo "used is part of this Triton cloud, then this should work:"
     echo ""
-    echo "    sdc-vmadm get $vmUuid | json customer_metadata.instPubKey > /tmp/imgapi-$vmUuid.id_rsa.pub"
-    echo "    sdc-useradm add-key -n \$(cat /tmp/imgapi-$vmUuid.id_rsa.pub | awk '{print $3}' | head -1) $mantaUser /tmp/imgapi-$vmUuid.id_rsa.pub"
-    XXX # TEST THIS
+    echo "    sdc-vmadm get $vmUuid \\"
+    echo "        | json customer_metadata.instPubKey > /tmp/imgapi.id_rsa.pub"
+    echo "    keyname=\$(cat /tmp/imgapi.id_rsa.pub | head -1 | awk '{print \$3}')"
+    echo "    sdc-useradm add-key -n \$keyname $mantaUser /tmp/imgapi.id_rsa.pub"
+    echo ""
+    echo "If the Manta is part of a separate cloud then, for an appropriate"
+    echo "Triton CLI profile, the following might work:"
+    echo ""
+    echo "    triton inst get $ALIAS | json metadata.instPubKey | \\"
+    echo "        | triton -p PROFILE key add -"
+    echo "* * *"
 fi
 
-#XXX if configured for manta
-#- emit message about needing to add the generated pubkey to the Manta
-#  user. Show command for that
 
-# Poll until get a 200 status ping.
-#XXX
 
 # TODO: Would like to have ping be 503 if cannot connect to Manta (if
 # configured for Manta. Then have this script gracefully handle that.
+
+exit 0
